# Generated by Django 2.0.2 on 2018-08-11 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
